apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::381844760599:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1M4A7787AXY0W
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws::iam::381844760599:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-06T11:51:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1644"
  uid: c9c65567-9732-47ec-9873-bd0642ccd692
